# Building blocks of tensorflow
- scalar: single value: (10)
- vector: single dimension: [1, 2, 3]
- matrix: two dimensions: \
     [1, 2, 3,\
     4, 5, 6,\
     7, 8, 9] 
- tensor: three dimensions

In [41]:
import tensorflow as tf
import numpy as np

In [17]:
v1 = tf.Variable("Hello", tf.string) # string tensor
v2 = tf.Variable([1,2], dtype=tf.uint32)
c1 = tf.constant([1,2,3]) # list of int constant

In [18]:
# defining shape
t1 = tf.constant([4,6], shape=(2,), dtype=tf.uint32)
v2 = tf.Variable([[1,2],[3,4]], shape=(2,2), dtype=tf.uint32)

# tf.constant has extra properties to tf.Variable 

In [36]:
# tf.constant can populate a tensor with a single value:
tensor1 = tf.constant(-1.0, shape=[2,3])
tensor1.numpy()

array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)

In [30]:
# tf.constant can reshape a single list into a matrix format
tensor2 = tf.constant([1,2,3,4,5,6], shape=(2,3))
tensor2.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Math operations

In [35]:
addition = tf.add([1,2], [3,4])
addition.numpy()

array([4, 6], dtype=int32)

In [32]:
total = tf.reduce_sum([1,2,3])
total.numpy()

6

In [37]:
squared = tf.square(5)
print("{}".format(squared))

25


In [38]:
# operator overloading allows neat tricks such as: 
square_then_add = tf.square(2) + tf.square(3)
print("{}".format(square_then_add ))

13


In [42]:
# tf is compatible with numpy 
np.multiply(total, squared)

150

# Broadcasting
adding or subtracting two tensors of different dimensions is handled in a way so that tensor with fewer dimensions matches the tensor with more dimensions

In [39]:
a = tf.constant([[1,2], [3,4]])
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [43]:
# Cast to different datatype

In [44]:
tf.cast(a, dtype=tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>